#pragma once

#include "../../../lib/sh_protocol/src/DeviceTypes.h"

// Konkretes Geraet: net_sen-Umweltpfad mit BME280 + VEML7700 + digitalem Regensensor.
// Regen wird aktuell als Event gemeldet; der net_sen-State-Payload hat noch kein Regenfeld.

#define NET_SEN_DEVICE_ID "NET-SEN-002"
#define NET_SEN_DEVICE_NAME "NET-SEN Env BME280+VEML+Rain"
#define NET_SEN_FW_VARIANT "net_sen_env_bme280_veml_rain"
#define NET_SEN_DEVICE_CAPS (SH_CAP_TEMP | SH_CAP_HUM | SH_CAP_LUX | SH_CAP_PRESSURE | SH_CAP_RAIN)
#define NET_SEN_DEVICE_REPORTING_MODE SH_REPORTING_HYBRID

#define NET_SEN_ENABLE_I2C_BASE 1

#define NET_SEN_HELLO_RETRY_INTERVAL_MS 5000UL
#define NET_SEN_HEARTBEAT_INTERVAL_MS 20000UL
#define NET_SEN_DEFAULT_REPORT_INTERVAL_S 10U
#define NET_SEN_DEFAULT_SENSOR_SEND_INTERVAL_S 10U
#define NET_SEN_STATE_INTERVAL_MS (NET_SEN_DEFAULT_REPORT_INTERVAL_S * 1000UL)
#define NET_SEN_MIN_REPORT_INTERVAL_S 5U
#define NET_SEN_MAX_REPORT_INTERVAL_S 600U
#define NET_SEN_LOOP_INTERVAL_MS 50UL

#define NET_SEN_ENV_BME280_VEML_RAIN_SENSOR_READ_INTERVAL_MS 2500UL
#define NET_SEN_ENV_BME280_VEML_RAIN_ERROR_LOG_INTERVAL_MS 15000UL
#define NET_SEN_ENV_BME280_VEML_RAIN_SNAPSHOT_LOG_INTERVAL_MS 30000UL

#define NET_SEN_ENV_BME280_VEML_RAIN_TEMP_DELTA_01C 10
#define NET_SEN_ENV_BME280_VEML_RAIN_HUM_DELTA_01PCT 50U
#define NET_SEN_ENV_BME280_VEML_RAIN_LUX_DELTA 25U
#define NET_SEN_ENV_BME280_VEML_RAIN_PRESSURE_DELTA_PA 30UL

#define NET_SEN_ENV_BME280_PRIMARY_ADDRESS 0x76
#define NET_SEN_ENV_BME280_FALLBACK_ADDRESS 0x77
#define NET_SEN_ENV_VEML7700_FIRST_READ_DELAY_MS 1050UL
