#pragma once

#define PIN_RELAY_1 10
#define PIN_SENSOR_SDA 0
#define PIN_SENSOR_SCL 1
#define PIN_PIR 6
#define PIN_STATUS_LED -1

#define RELAY_1_ACTIVE_HIGH 1

#define SETUP_BUTTON_PIN -1
#define SETUP_BUTTON_ACTIVE_LOW 1
#define SETUP_BUTTON_HOLD_MS 5000UL
#define SETUP_INDICATOR_LED_PIN PIN_STATUS_LED
#define SETUP_INDICATOR_LED_ACTIVE_HIGH 1
#define SETUP_INDICATOR_BLINK_MS 500UL
