#pragma once

#include <stdint.h>

#include "../../../lib/sh_protocol/src/DeviceTypes.h"

#ifndef BAT_SEN_DEVICE_ID
#define BAT_SEN_DEVICE_ID "bat_sen_base_01"
#endif

#ifndef BAT_SEN_DEVICE_NAME
#define BAT_SEN_DEVICE_NAME "BAT-SEN Base"
#endif

#ifndef BAT_SEN_FW_VARIANT
#define BAT_SEN_FW_VARIANT "bat_sen_base"
#endif

#ifndef BAT_SEN_DEVICE_CAPS
#define BAT_SEN_DEVICE_CAPS SH_CAP_BATTERY
#endif

#ifndef BAT_SEN_DEBUG_ENABLED
#define BAT_SEN_DEBUG_ENABLED 1
#endif

#ifndef BAT_SEN_REPORTING_MODE
#define BAT_SEN_REPORTING_MODE SH_REPORTING_SLEEP_EVENT
#endif

#ifndef BAT_SEN_WLAN_CHANNEL
#define BAT_SEN_WLAN_CHANNEL 6
#endif

#ifndef BAT_SEN_HELLO_RETRY_INTERVAL_MS
#define BAT_SEN_HELLO_RETRY_INTERVAL_MS 5000UL
#endif

#ifndef BAT_SEN_DISCOVERY_WINDOW_MS
#define BAT_SEN_DISCOVERY_WINDOW_MS 25000UL
#endif

#ifndef BAT_SEN_DEFAULT_REPORT_INTERVAL_S
#define BAT_SEN_DEFAULT_REPORT_INTERVAL_S 900U
#endif

#ifndef BAT_SEN_DEFAULT_WAKE_INTERVAL_S
#define BAT_SEN_DEFAULT_WAKE_INTERVAL_S 900U
#endif

#ifndef BAT_SEN_DEFAULT_RX_WINDOW_MS
#define BAT_SEN_DEFAULT_RX_WINDOW_MS 5000U
#endif

#ifndef BAT_SEN_MIN_REPORT_INTERVAL_S
#define BAT_SEN_MIN_REPORT_INTERVAL_S 30U
#endif

#ifndef BAT_SEN_MAX_REPORT_INTERVAL_S
#define BAT_SEN_MAX_REPORT_INTERVAL_S 65535U
#endif

#ifndef BAT_SEN_MIN_WAKE_INTERVAL_S
#define BAT_SEN_MIN_WAKE_INTERVAL_S 30U
#endif

#ifndef BAT_SEN_MAX_WAKE_INTERVAL_S
#define BAT_SEN_MAX_WAKE_INTERVAL_S 65535U
#endif

#ifndef BAT_SEN_MIN_RX_WINDOW_MS
#define BAT_SEN_MIN_RX_WINDOW_MS 1000U
#endif

#ifndef BAT_SEN_MAX_RX_WINDOW_MS
#define BAT_SEN_MAX_RX_WINDOW_MS 60000U
#endif

#ifndef BAT_SEN_LOOP_INTERVAL_MS
#define BAT_SEN_LOOP_INTERVAL_MS 25UL
#endif

#ifndef BAT_SEN_BATTERY_SAMPLE_INTERVAL_MS
#define BAT_SEN_BATTERY_SAMPLE_INTERVAL_MS 5000UL
#endif

#ifndef BAT_SEN_BATTERY_STATE_DELTA_MV
#define BAT_SEN_BATTERY_STATE_DELTA_MV 10U
#endif

#ifndef BAT_SEN_BATTERY_STATE_DELTA_PCT
#define BAT_SEN_BATTERY_STATE_DELTA_PCT 1U
#endif

#ifndef BAT_SEN_BATTERY_EMPTY_MV
#define BAT_SEN_BATTERY_EMPTY_MV 3000U
#endif

#ifndef BAT_SEN_BATTERY_FULL_MV
#define BAT_SEN_BATTERY_FULL_MV 4200U
#endif

#ifndef BAT_SEN_BATTERY_DIVIDER_NUM
#define BAT_SEN_BATTERY_DIVIDER_NUM 2U
#endif

#ifndef BAT_SEN_BATTERY_DIVIDER_DEN
#define BAT_SEN_BATTERY_DIVIDER_DEN 1U
#endif

#ifndef BAT_SEN_ENABLE_DEEP_SLEEP
#define BAT_SEN_ENABLE_DEEP_SLEEP 1
#endif

#ifndef BAT_SEN_ENABLE_ADC_BATTERY
#define BAT_SEN_ENABLE_ADC_BATTERY 1
#endif

#ifndef BAT_SEN_ENABLE_GPIO_WAKE
#define BAT_SEN_ENABLE_GPIO_WAKE 0
#endif

constexpr char DEVICE_ID[] = BAT_SEN_DEVICE_ID;
constexpr char DEVICE_NAME[] = BAT_SEN_DEVICE_NAME;
constexpr char FW_VARIANT[] = BAT_SEN_FW_VARIANT;
constexpr bool DEVICE_DEBUG_AKTIV = BAT_SEN_DEBUG_ENABLED != 0;
constexpr uint16_t DEVICE_CAPS = (uint16_t)BAT_SEN_DEVICE_CAPS;

constexpr uint8_t DEVICE_META_SCHEMA_VERSION = SH_META_SCHEMA_VERSION_CURRENT;
constexpr uint8_t DEVICE_CONTROL_MODE = SH_CONTROL_MODE_NONE;
constexpr uint8_t DEVICE_CONFIG_PROFILE = SH_PROFILE_NONE;
constexpr uint8_t DEVICE_REPORTING_MODE = BAT_SEN_REPORTING_MODE;

constexpr int WLAN_KANAL = BAT_SEN_WLAN_CHANNEL;

constexpr unsigned long HELLO_RETRY_INTERVAL_MS = BAT_SEN_HELLO_RETRY_INTERVAL_MS;
constexpr unsigned long DISCOVERY_WINDOW_MS = BAT_SEN_DISCOVERY_WINDOW_MS;
constexpr unsigned long DEFAULT_REPORT_INTERVAL_S = BAT_SEN_DEFAULT_REPORT_INTERVAL_S;
constexpr unsigned long DEFAULT_WAKE_INTERVAL_S = BAT_SEN_DEFAULT_WAKE_INTERVAL_S;
constexpr unsigned long DEFAULT_RX_WINDOW_MS = BAT_SEN_DEFAULT_RX_WINDOW_MS;
constexpr unsigned long MIN_REPORT_INTERVAL_S = BAT_SEN_MIN_REPORT_INTERVAL_S;
constexpr unsigned long MAX_REPORT_INTERVAL_S = BAT_SEN_MAX_REPORT_INTERVAL_S;
constexpr unsigned long MIN_WAKE_INTERVAL_S = BAT_SEN_MIN_WAKE_INTERVAL_S;
constexpr unsigned long MAX_WAKE_INTERVAL_S = BAT_SEN_MAX_WAKE_INTERVAL_S;
constexpr unsigned long MIN_RX_WINDOW_MS = BAT_SEN_MIN_RX_WINDOW_MS;
constexpr unsigned long MAX_RX_WINDOW_MS = BAT_SEN_MAX_RX_WINDOW_MS;
constexpr unsigned long LOOP_INTERVAL_MS = BAT_SEN_LOOP_INTERVAL_MS;
constexpr unsigned long BATTERY_SAMPLE_INTERVAL_MS = BAT_SEN_BATTERY_SAMPLE_INTERVAL_MS;
constexpr uint16_t BATTERY_STATE_DELTA_MV = BAT_SEN_BATTERY_STATE_DELTA_MV;
constexpr uint8_t BATTERY_STATE_DELTA_PCT = BAT_SEN_BATTERY_STATE_DELTA_PCT;

constexpr uint16_t BATTERY_EMPTY_MV = BAT_SEN_BATTERY_EMPTY_MV;
constexpr uint16_t BATTERY_FULL_MV = BAT_SEN_BATTERY_FULL_MV;
constexpr uint16_t BATTERY_DIVIDER_NUM = BAT_SEN_BATTERY_DIVIDER_NUM;
constexpr uint16_t BATTERY_DIVIDER_DEN = BAT_SEN_BATTERY_DIVIDER_DEN;

constexpr bool DEEP_SLEEP_AKTIV = BAT_SEN_ENABLE_DEEP_SLEEP != 0;
constexpr bool BATTERY_ADC_AKTIV = BAT_SEN_ENABLE_ADC_BATTERY != 0;
constexpr bool GPIO_WAKE_AKTIV = BAT_SEN_ENABLE_GPIO_WAKE != 0;

static_assert(BATTERY_DIVIDER_DEN > 0U, "BAT_SEN_BATTERY_DIVIDER_DEN darf nicht 0 sein.");
static_assert(BATTERY_FULL_MV > BATTERY_EMPTY_MV, "BAT_SEN_BATTERY_FULL_MV muss groesser sein als BAT_SEN_BATTERY_EMPTY_MV.");
static_assert(DEFAULT_REPORT_INTERVAL_S >= MIN_REPORT_INTERVAL_S, "BAT_SEN_DEFAULT_REPORT_INTERVAL_S unter Minimum.");
static_assert(DEFAULT_REPORT_INTERVAL_S <= MAX_REPORT_INTERVAL_S, "BAT_SEN_DEFAULT_REPORT_INTERVAL_S ueber Maximum.");
static_assert(DEFAULT_WAKE_INTERVAL_S >= MIN_WAKE_INTERVAL_S, "BAT_SEN_DEFAULT_WAKE_INTERVAL_S unter Minimum.");
static_assert(DEFAULT_WAKE_INTERVAL_S <= MAX_WAKE_INTERVAL_S, "BAT_SEN_DEFAULT_WAKE_INTERVAL_S ueber Maximum.");
static_assert(DEFAULT_RX_WINDOW_MS >= MIN_RX_WINDOW_MS, "BAT_SEN_DEFAULT_RX_WINDOW_MS unter Minimum.");
static_assert(DEFAULT_RX_WINDOW_MS <= MAX_RX_WINDOW_MS, "BAT_SEN_DEFAULT_RX_WINDOW_MS ueber Maximum.");
