#pragma once

#include <stdint.h>

#include "../../../lib/sh_protocol/src/DeviceTypes.h"

#ifndef NET_SEN_DEVICE_ID
#define NET_SEN_DEVICE_ID "net_sen_base_01"
#endif

#ifndef NET_SEN_DEVICE_NAME
#define NET_SEN_DEVICE_NAME "NET-SEN Base"
#endif

#ifndef NET_SEN_FW_VARIANT
#define NET_SEN_FW_VARIANT "net_sen_base"
#endif

#ifndef NET_SEN_DEVICE_CAPS
#define NET_SEN_DEVICE_CAPS 0U
#endif

#ifndef NET_SEN_DEBUG_ENABLED
#define NET_SEN_DEBUG_ENABLED 1
#endif

#ifndef NET_SEN_WLAN_CHANNEL
#define NET_SEN_WLAN_CHANNEL 6
#endif

#ifndef NET_SEN_HELLO_RETRY_INTERVAL_MS
#define NET_SEN_HELLO_RETRY_INTERVAL_MS 5000UL
#endif

#ifndef NET_SEN_HEARTBEAT_INTERVAL_MS
#define NET_SEN_HEARTBEAT_INTERVAL_MS 60000UL
#endif

#ifndef NET_SEN_STATE_INTERVAL_MS
#define NET_SEN_STATE_INTERVAL_MS 60000UL
#endif

#ifndef NET_SEN_DEFAULT_REPORT_INTERVAL_S
#define NET_SEN_DEFAULT_REPORT_INTERVAL_S (NET_SEN_STATE_INTERVAL_MS / 1000UL)
#endif

#ifndef NET_SEN_DEFAULT_SENSOR_SEND_INTERVAL_S
#define NET_SEN_DEFAULT_SENSOR_SEND_INTERVAL_S NET_SEN_DEFAULT_REPORT_INTERVAL_S
#endif

#ifndef NET_SEN_ENABLE_I2C_BASE
#define NET_SEN_ENABLE_I2C_BASE 0
#endif

#ifndef NET_SEN_DEVICE_REPORTING_MODE
#define NET_SEN_DEVICE_REPORTING_MODE SH_REPORTING_PERIODIC
#endif

#ifndef NET_SEN_LOOP_INTERVAL_MS
#define NET_SEN_LOOP_INTERVAL_MS 50UL
#endif

#ifndef NET_SEN_MIN_REPORT_INTERVAL_S
#define NET_SEN_MIN_REPORT_INTERVAL_S 10U
#endif

#ifndef NET_SEN_MAX_REPORT_INTERVAL_S
#define NET_SEN_MAX_REPORT_INTERVAL_S 3600U
#endif

constexpr char DEVICE_ID[] = NET_SEN_DEVICE_ID;
constexpr char DEVICE_NAME[] = NET_SEN_DEVICE_NAME;
constexpr char FW_VARIANT[] = NET_SEN_FW_VARIANT;
constexpr bool DEVICE_DEBUG_AKTIV = NET_SEN_DEBUG_ENABLED != 0;
constexpr uint16_t DEVICE_CAPS = (uint16_t)NET_SEN_DEVICE_CAPS;
constexpr bool I2C_BASIS_AKTIV = NET_SEN_ENABLE_I2C_BASE != 0;

constexpr uint8_t DEVICE_META_SCHEMA_VERSION = SH_META_SCHEMA_VERSION_CURRENT;
constexpr uint8_t DEVICE_CONTROL_MODE = SH_CONTROL_MODE_NONE;
constexpr uint8_t DEVICE_CONFIG_PROFILE = SH_PROFILE_NONE;
constexpr uint8_t DEVICE_REPORTING_MODE = NET_SEN_DEVICE_REPORTING_MODE;

constexpr unsigned long HELLO_RETRY_INTERVAL_MS = NET_SEN_HELLO_RETRY_INTERVAL_MS;
constexpr unsigned long HEARTBEAT_INTERVAL_MS = NET_SEN_HEARTBEAT_INTERVAL_MS;
constexpr unsigned long STATE_INTERVAL_MS = NET_SEN_STATE_INTERVAL_MS;
constexpr uint32_t DEFAULT_REPORT_INTERVAL_S = NET_SEN_DEFAULT_REPORT_INTERVAL_S;
constexpr uint32_t DEFAULT_SENSOR_SEND_INTERVAL_S = NET_SEN_DEFAULT_SENSOR_SEND_INTERVAL_S;
constexpr unsigned long LOOP_INTERVAL_MS = NET_SEN_LOOP_INTERVAL_MS;
constexpr uint32_t MIN_REPORT_INTERVAL_S = NET_SEN_MIN_REPORT_INTERVAL_S;
constexpr uint32_t MAX_REPORT_INTERVAL_S = NET_SEN_MAX_REPORT_INTERVAL_S;
constexpr int WLAN_KANAL = NET_SEN_WLAN_CHANNEL;
