[platformio]
default_envs = master

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
    -D SH_PLATFORMIO=1

[env:master]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<basetypes/master/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    knolleary/PubSubClient @ ^2.8

[env:net_erl_kitchen_light]
board = esp32-c3-devkitm-1

[env:net_erl_hall_light]
board = esp32-c3-devkitm-1

[env:net_zrl_shutter]
board = esp32-c3-devkitm-1

[env:net_sen_room]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<devices/net_sen_room/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.3.0
    adafruit/Adafruit VEML7700 Library @ ^2.1.6

[env:net_sen_env_bme680_veml]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<devices/net_sen_env_bme680_veml/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit BME680 Library @ ^2.0.4
    adafruit/Adafruit VEML7700 Library @ ^2.1.6
    adafruit/ENS160 - Adafruit Fork @ ^3.0.1

[env:net_sen_dht22_reference]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<devices/net_sen_dht22_reference/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

[env:bat_sen]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<basetypes/bat_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:bat_sen_window_contact]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<devices/bat_sen_window_contact/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:bat_sen_rain]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<devices/bat_sen_rain/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
