[platformio]
default_envs = master

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:master]
board = esp32-c3-devkitm-1

[env:net_erl_kitchen_light]
board = esp32-c3-devkitm-1

[env:net_erl_hall_light]
board = esp32-c3-devkitm-1

[env:net_zrl_shutter]
board = esp32-c3-devkitm-1

[env:net_sen_room]
board = esp32-c3-devkitm-1

[env:bat_sen_window_contact]
board = esp32-c3-devkitm-1

[env:bat_sen_rain]
board = esp32-c3-devkitm-1
